### ISSUE TITLE
Разбор типовых ошибок в OS

### ISSUE THREAD

**Issue by nicl-nno** [aimclub/open-source-ops#14]
Тут наоборот - предлагается создать подборку "анти-паттернов" - что и почему люди обычно делают не так, создавая и управляя OS-проектами.

**Comment by 1spb-org** [comment]
Поддерживаю.

**Comment by ZharkovKirill** [comment]
Крайне полезная [лекция]( https://www.youtube.com/watch?v=9wA5yIM3pkI) от CS центра на эту тему.
