### ISSUE TITLE
Create beatuful auto-generated webpage with all materials

### ISSUE THREAD

**Issue by nicl-nno** [aimclub/open-source-ops#40]
Не уверен насчет read-the-docs, возможно тут лучше githubio подойдет.

**Comment by nicl-nno** [comment]
@DenisSidoren не знаешь, как это проще всего сделать?

**Comment by nicl-nno** [comment]
Не будет проще через github pages? Тогда вообще ничего не нужно будет менять по структуре.

**Comment by DenisSidoren** [comment]
@nicl-nno  я с их генерацией не сталкивался пока, поэтому не могу сказать, будет ли это проще и удобнее
